#!/usr//bin/python3
def raise_exception():
    raise TypeError("Value Exception has been raised!")
